--- mysql
ALTER TABLE `person` ADD COLUMN `SYS__CREATE_OR_UPDATE_TIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP;

--- oracle
ALTER TABLE "JACK"."PERSON" ADD ( "SYS__CREATE_OR_UPDATE_TIME" TIMESTAMP(0)  DEFAULT sysdate NULL);
CREATE OR REPLACE TRIGGER "JACK"."tn_NAME" BEFORE UPDATE ON "JACK"."PERSON" FOR EACH ROW BEGIN :NEW.SYS__CREATE_OR_UPDATE_TIME := SYSDATE ; END ;

--- MS SQL
ALTER TABLE [PERSON] ADD [SYS__CREATE_OR_UPDATE_TIME] datetime NULL DEFAULT (getdate());
UPDATE [PERSON] SET [SYS__CREATE_OR_UPDATE_TIME] = getdate() WHERE [SYS__CREATE_OR_UPDATE_TIME] IS NULL;
CREATE TRIGGER tn_name ON [PERSON] AFTER UPDATE AS BEGIN UPDATE [PERSON] SET [SYS__CREATE_OR_UPDATE_TIME] = getdate() WHERE [SYS__BACKUP__INDEX] IN (SELECT [SYS__BACKUP__INDEX] FROM [deleted]); END ;










